client/nginx.go
docker/nginx.conf
tests/client_test.go

Full support for key-value endpoints for both http and stream contexts.

Add key-value support

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Follow best practices and have code of conduct in project root.
src https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-manually

Move code of conduct to project root

---

CONTRIBUTING.md
Makefile
tests/client_test.go

Add a Makefile option to run go linter in dev.

Add lint option to Makefile and fix lint issues

---

Makefile
README.md
client/nginx.go

* Update API version to v4 (now min required NGINX Plus version for the go-client is R18)
* Fix the `stream` endpoints with the new error code (ref: https://github.com/nginxinc/nginx-prometheus-exporter/issues/45)
* Removed `GOCACHE` as this is not used in Go 1.12 anymore (ref: https://tip.golang.org/doc/go1.12#gocache)
PS: I think the tests that were already in `client_no_stream_test.go` cover the case of when the stream is not present as now we are returning an empty map of `StreamServerZones` or `StreamUpstreams` when path not found is returned as error.

Update to API v4 and fix stream endpoints

---

Makefile
README.md
client/nginx.go
docker/nginx.conf
tests/client_test.go

Add Stream Zone Sync (http://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_stream_zone_sync) metrics in the client.

Add zone sync endpoint to stats

---

client/nginx.go
tests/client_no_stream_test.go
tests/client_test.go

NGINX Plus does not return StreamZoneSync metrics if there is no sync zone configured. Because of this, we need to make these a pointer to the struct so we can check if the metrics are present or not (instead of returning an empty struct with zeroes)
This will require the user to be careful when using the `Stats.StreamZoneSync` field, as it can be `nil`.

Make zone sync struct optional

---

client/nginx.go

* `4xx` and `5xx` session metrics are not correctly unmarshalled. Instead
they are ignored. This is due to a typo.
Bug introduced in: https://github.com/nginxinc/nginx-plus-go-client/commit/c9fb4acf9c4aeb238b2e9121aecf9c4dbe525676

Fix session metrics for stream upstreams

---

client/nginx.go
tests/client_test.go

* Fix MaxFails in UpstreamServer and StreamUpstreamServer. Previously the default was `0` as opposed to the intended `1`.
* Improve test coverage for UpstreamServer and StreamUpstreamServer. The following cases were added
* Adding defaultUpstream
* Setting MaxConns
* Setting MaxFails
* Setting FailTimeout

Fix MaxFails default and Add test coverage for UpstreamServers

---

client/nginx.go
docker/test.conf
tests/client_test.go

Fixes #28
Extend the go client to support additional parameters in upstream servers:
`route`
`backup`
`down`
`drain`
`weight`
`service`
Make sure that when adding an upstream server with unspecified parameters, the values of those parameters in NGINX Plus API are set with their default values.

Add Additional Upstream Server Parameters

---

Makefile
client/nginx.go
docker/nginx.conf
docker/test.conf
tests/client_test.go

Support the newly added per location and resolver metrics.
APIVersion upgrade 4 -> 5
NGINX Plus version upgrade R18 -> R19

Support location zones and resolver metrics in go client

---

Makefile

- Add support for parameterisation in Makefile

Add support for Makefile parameterisation

---

client/nginx.go
client/nginx_test.go
tests/client_test.go

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

Add support for updating upstream servers

---

client/nginx.go

Adding support for /slabs API endpoint so we can monitor shared memory zone usage.

Add functionality to get /slabs

---

client/nginx.go

- Adding support for /processes API endpoint so we can monitor the count of respawned processes.
- Export Get-from-API functions 

Add support for /processes and export functions

---

.github/workflows/ci.yml
Makefile
build/ci/Jenkinsfile

Switch continuous integration to Github Action workflows.

Migrate continuous integration to Github workflows

---

.github/dependabot.yml

Fix Dockerfile location in dependabot config

---

client/nginx.go
docker/test.conf
tests/client_test.go

Retrieves cache stats from the [http/caches](https://nginx.org/en/docs/http/ngx_http_api_module.html#http_caches_) endpoint

Add cache stats

---

Makefile
docker/Dockerfile

- Update NGINX Plus to R24
- Updated Docker base image to buster
- Mount nginx cert and key at build time instead of copying into the container
- Updated golangci-lint to use latest

Update Dockerfile, NGINX and golangci-lint versions

---

.github/workflows/lint.yml
.golangci.yml
Makefile
client/nginx.go
client/nginx_test.go
tests/client_no_stream_test.go
tests/client_test.go

Add config for golangci-lint and fix errors
TODO:

Add golangci-lint config

---

client/nginx.go

Erroneously removed the `resp.Body.Close()`

Restore closing the HTTP response

---

.golangci.yml

Adding `revive` (replacement for the deprecated `golint`) with the [recommended](https://github.com/mgechev/revive#recommended-configuration) configuration

Add revive linter with recommended config

---

.github/workflows/ci.yml
Makefile
README.md

Use Docker action to build the image

User Docker Build action in CI

---

docker/Dockerfile
tests/client_no_stream_test.go
tests/client_test.go

This commit fixes the below error we have been seeing in the pipeline by pulling the virtual package from the version specific repo:
```
#11 11.69 Package nginx-plus-r25 is a virtual package provided by:
#11 11.69   nginx-plus 25-2~buster [Not candidate version]
#11 11.69   nginx-plus 25-1~buster [Not candidate version]
#11 11.69 
#11 11.75 E: Package 'nginx-plus-r25' has no installation candidate
```

Fix virtual package error

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/fossa.yml
.github/workflows/lint.yml
.github/workflows/release-drafter.yml
CONTRIBUTING.md

Updates docs and CI for name change from `master` to `main`

Rename main branch

---

.github/workflows/ci.yml
docker/Dockerfile

Dockerfile 1.4 now supports using here-documents https://github.com/moby/buildkit/blob/dockerfile/1.4.0/frontend/dockerfile/docs/syntax.md#here-documents
This improves readability without all the `&&` and `\`

Use here-documents style in Dockerfile

---

.github/workflows/dependabot-auto-merge.yml

Enables auto-merge. The PR will only be merged after the checks are satisfied.

Add workflow to enable auto-merge for dependabot

---

README.md
client/nginx.go

Closes #109 
I used the names and response codes from https://www.nginx.com/resources/wiki/extending/api/http/

Add support for API version 7

---

README.md
client/nginx.go
tests/client_test.go

Add support for API version 8

---

.github/workflows/ci.yml
.gitignore
.goreleaser.yaml
CHANGELOG.md

Docs and workflow changes for release `0.10.0`. 
Additionally:
- Added automatic publish on tag with release drafter
- GoReleaser used to announce the release on the community slack channel

Release 0.10.0

---

client/nginx.go

Replace deprecated package ```io/ioutil``` with ```io```

Remove dependency on a deprecated package

---

.goreleaser.yaml

The correct channel is `#announcements`

Update Slack announce channel

---

.github/workflows/ci.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/fossa.yml
.github/workflows/lint.yml
.github/workflows/notifications.yml
.github/workflows/release-drafter.yml
.github/workflows/stale.yml

Updates the runners to the latest ubuntu [actions/runner-images@main/images/linux/Ubuntu2204-Readme.md](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md?rgh-link-date=2022-10-12T05%3A37%3A23Z)

Update GitHub Actions runners to Ubuntu 22.04

---

.github/workflows/ci.yml
Makefile
compose.yaml
docker/Dockerfile
docker/nginx.conf
docker/nginx_no_stream.conf

Simplifies tests setup using docker compose

Use Docker Compose for tests

---

README.md

* Fix api support range in readme to include api version `9` since: https://github.com/nginxinc/nginx-plus-go-client/commit/80901b0dc044939e6423e81f20f3baedf697747c

Fix api support range in readme

---

client/nginx.go
client/nginx_test.go
tests/client_no_stream_test.go
tests/client_test.go

This change makes creating a client more flexible:
- passing an HTTP Client is now optional (a default one will be used otherwise)
- passing the API version is now optional (the latest is used by default)
- connecting to the API endpoint on creation is controlled by a parameter (disabled by default)
**Note: This is a breaking change**

Refactor NGINX Client to use options

---

CHANGELOG.md
README.md

Release 1.0.0

---

client/nginx.go
client/nginx_test.go
go.mod
go.sum

This changes is required for the use case where someone doesn't have streams configured in their nginx.conf and want to prevent 404 errors from being logged in the NGINX access log.
```
127.0.0.1 - - [05/Oct/2023:13:10:29 +0000] "GET /api//8/stream/upstreams HTTP/1.1" 404 183 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [05/Oct/2023:13:10:29 +0000] "GET /api//8/stream/zone_sync HTTP/1.1" 404 183 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [05/Oct/2023:13:10:29 +0000] "GET /api//8/stream/limit_conns HTTP/1.1" 404 183 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [05/Oct/2023:13:10:44 +0000] "GET /api//8/stream/server_zones HTTP/1.1" 404 183 "-" "Go-http-client/1.1" "-"
```

Add checks to see if stream endpoints exist before calling them

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
client/nginx.go
go.mod
go.sum

Updates the version of go and removes external `slices` dependency that is now part of go `1.21`

Bump Go to 1.21

---

client/nginx.go
client/nginx_test.go

This PR addresses #183 to include extended SSL stats added since N+ R28

Update extended SSL stats

---

.golangci.yml
.pre-commit-config.yaml
client/nginx.go
tests/client_test.go

Enables new linters and changes the code to fix the problems. 
The main change is `fieldalignment` that should result in performance improvements.

Enable more linters

---

.github/labeler.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml
.yamllint.yaml

Adds `yamllint` and fixes files

Add yamllint

---

client/nginx.go
client/nginx_test.go
tests/client_test.go

This PR should resolve the issue reported here: https://github.com/nginxinc/nginx-plus-go-client/issues/216

Fix TestStatsNoStream

---

.golangci.yml
client/nginx.go
client/nginx_test.go
tests/client_test.go

Adds more linters and fixes the errors

Add more linters

---

release-process.md

Add release process

---

.golangci.yml
client/nginx.go
client/nginx_test.go

Adds linters that specifically check for bugs

Add linters that check for bugs

---

client/nginx.go

According to the docs here https://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_http_upstream, the keepalive field is called `keepalive` not `keepalives`.
This PR fixes the field name in the Upstream struct.

Update keepalive field for http upstreams

---

.github/workflows/ci.yml
.goreleaser.yaml

Adds missing setting to `goreleaser` and runs the `setup-go` action only on release.
Adds go 1.21 to the matrix of versions to test.

Automatically close milestones

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
release-process.md

The Contributing Guidelines had new sections that were never added to the TOC.
With doctoc we can keep the TOCs up to date automatically.

Add doctoc to automatically generate TOCs

---

client/nginx.go
client/nginx_test.go

Add the ability to configure the context timeout period for API requests. Currently it is hardcoded to 10 seconds. Added a configuration parameter to override this value.

added context timeout configuration for API requests

---

client/nginx.go
client/nginx_test.go
docker/Dockerfile

Add GetMaxAPIVersion to get max supported API

---

.github/workflows/ci.yml
compose.yaml

Now that go 1.23 is stable, we want to add 1.22 to the list of versions we test.

Add go 1.22 to unit tests

---

.golangci.yml
client/nginx.go

Improves error handling and inspection.

Use wrapped static errors

---

.github/workflows/dependency-review.yml
.github/workflows/lint.yml

The `actions/dependency-review-action` only works on PRs and we want to enforce the check. There's no option to enforce a check only on PR and not on Merge Queue. This makes the run in the Merge Queue pass.

Skip dependency review run on merge queue

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml

Skips the entire job when triggered by a merge queue

Skip workflow runs the right way

---

.github/workflows/ci.yml

GoReleaser needs write permissions to automatically close milestones. 

Add permissions for GoReleaser

---

.golangci.yml
client/nginx.go
client/nginx_test.go
tests/client_no_stream_test.go
tests/client_test.go

Support cancellation of NGINX Plus API calls

---

go.mod
tests/client_no_stream_test.go
tests/client_test.go

The module needs to be updated to use `v2`

Update go module to use v2

---

client/nginx.go
client/nginx_test.go

Add function GetNginxLicense() which returns a struct of type `NginxLicense`
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to
that issue here in this description (not in the title of the PR).

add license support

---

client/nginx.go
client/nginx_test.go

**Client's UpdateHTTPServers and UpdateStreamServers methods now attempt to update all servers and return a combined error**
Previously these methods would return as soon as an error was encountered. Now they attempt to apply all the server updates and collect all errors encountered along the way. The reasoning behind this is that we want to apply as many of the desired changes as we possibly can and don't want any transitory errors that may affect a single server update to cause all the rest of the updates to be skipped.
Use case:
I work for the NGINXaaS for Azure team and we using the plus client to apply on-the-fly upstream server updates to deployments linked with kubernetes clusters. Our aim is to react to scaling and other events on the cluster by applying the server updates to the …

Client server updates are attempted in full

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/dependency-review.yml
.github/workflows/labeler.yml
CHANGELOG.md
CODEOWNERS
CONTRIBUTING.md
README.md
compose.yaml
go.mod
release-process.md
renovate.json
tests/client_no_stream_test.go
tests/client_test.go

Updates all the references to `nginxinc`

Update from nginxinc to nginx

---

client/nginx.go
client/nginx_test.go
tests/client_test.go

Update `UpdateHTTPServers` and `UpdateStreamServers`:
- No longer make extra `GET` requests for each `PUT` and `DELETE` request.
- Removes identical duplicate servers.
- Returns errors for duplicate servers with different parameters.
Adds `Content-Type` header to NGINX client `PATCH` requests.

Update servers improvements

---

client/nginx.go
client/nginx_test.go

This will allow users of the plus client to check errors and decide what further action to take. This fix follows the advice of commentators who counsel users of go to assert errors for behavior, not type. https://dave.cheney.net/2014/12/24/inspecting-errors The user would create a simple error interface including Status() and Code() methods and then could use errors.As() to cast the internalError to their own interface type. For example, if the user attempts to delete an upstream server using the client, the user can check the error returned for a http.StatusNotFound code, and if present, can make their application take no further action. If some error status code is returned, then the user can retry the delete. Previously in order to perform this kind of analysis the user would have to …

Make status code and NGINX error codes on internalError publicly accessible

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml
.golangci.yml
.pre-commit-config.yaml
Makefile
client/nginx_test.go
compose.yaml
docker/Dockerfile
go.mod
go.sum

Update all outdated dependencies in one PR as all of the existing automated PRs are not in a mergeable state
- Old renovate PRs are stuck on the F5 CLA bot
- golangci-lint had a major version bump and requires the existing configuration to be updated manually

Chore: update dependencies
