CHANGELOG.md
Makefile

Release 0.2

---

.travis.yml
README.md

Add a travis pipeline to run unit tests on each push.
Badges for the build, apache license and goreport added to README file

Add travis build, travis, go report and license badges

---

client/nginx_test.go
tests/client_test.go

* Simplify tests with `gofmt -s`. (Found by goreportcard)

Fix go style

---

Makefile

Update NGINX Plus version to R17

Update NGINX Plus version to R17

---

client/nginx.go

* Make the constants Stream and HTTP private
* Refactor addKeyValPair to use the  post helper method
* Add patch helper method
* Refactor modifyKeyValPair and deleteKeyValuePair to use the patch helper method
* Refactor deleteKeyValPairs to use the delete helper method
* Fix codestyle to be more consistent

Refactor client to use helper methods

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CONTRIBUTING.md
README.md
tests/client_no_stream_test.go
tests/client_test.go

The new name is more appropriate then the previous nginx-plus-go-sdk.
For upgrading, please add a new dependency -
github.com/nginxinc/nginx-plus-go-client/client - to your project,
remove the old github.com/nginxinc/nginx-plus-go-sdk/client
and update the existing import paths accordingly.
- I didn't change the link in the changelog. The old link will continue to work - a visitor will be redirected. 

Rename project to nginx-plus-go-client

---

CHANGELOG.md

Release 0.3

---

client/nginx.go
tests/client_test.go

* Allow retrieving `MaxConns` of upstreams from the client
* Fix some typos

Add MaxConns support for UpstreamServer and StreamUpstreamServer

---

Makefile
build/ci/Jenkinsfile

* Adding automated testing for nightly and preview builds of NGINX+.

Add Jenkinsfile for automated nightly and preview testing

---

CHANGELOG.md
README.md

**FEATURES:**
- Additional Upstream Server Parameters. `route` `backup` `down` `drain` `weight` `service`
- Support `location zones` and `resolver` metrics
**BUGFIXES:**
- Fix `MaxFails` in UpstreamServer and StreamUpstreamServer and improved test coverage

Release 0.5.0

---

.travis.yml

Go 1.13 was released recently.
We need to update our projects to use Go 1.13
Make sure both travis files (if present) and Makefiles are updated.

Update Go version to 1.13

---

tests/client_test.go

* Add some test coverage for slab stats, which was added in: https://github.com/nginxinc/nginx-plus-go-client/pull/38

Add test coverage for Slabs

---

.travis.yml

Update Go version to 1.14

---

.github/workflows/ci.yml

Add internal Slack notification for failed builds.

Add Slack notification for failed builds

---

Makefile

Update Go version to 1.15

---

.github/workflows/ci.yml

Update Slack notifications

---

.github/workflows/ci.yml
.github/workflows/fossa.yml
.travis.yml

Retire Travis

---

.github/workflows/lint.yml
Makefile

Add lint workflow

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Remove ci trigger for docs changes

Remove ci trigger for docs changes

---

.github/workflows/ci.yml

Update workflow status version

Update workflow status version

---

client/nginx.go

Add support of NGINX PLUS API version 4 for N+ R18 and earlier.

Add support of N+ API version 4

---

.github/workflows/ci.yml

Build client stage wasn't running on nightly as scheduled events weren't one of the conditions

chore: build client and test on scheduled runs

---

.github/workflows/ci.yml

Nightly workflow isn't passing, and hasn't passed in a very long time. Disable for now until we can fix it.
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

Disable nightly for now

---

.github/workflows/ci.yml

It was removing the wrong line, causing the nightly to fail

Remove correct line in nightly

---

.github/workflows/ci.yml

Sed replacement in wrong line

---

.github/workflows/ci.yml

Updates the nightly run that uses the test repo

Fix nightly run with test repo

---

.github/workflows/ci.yml

Fix release step

---

.github/workflows/scorecard.yml
README.md

Adds OpenSSF scorecard workflow and badge

Add OpenSSF Scorecard

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
.markdownlint-cli2.yaml
.pre-commit-config.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
ISSUE_LIFECYCLE.md
README.md
SECURITY.md

Adds pre-commit and fixes existing issues

Add pre-commit and fix issues

---

docker/Dockerfile

Bump Debian to 12

---

.github/workflows/scorecard.yml

* Skip running OpenSSF check on forks which cannot run due to lack of secrets

Skip running OpenSSF check on forks

---

.github/workflows/ci.yml

Adds step to setup go for 1.21

Add setup go step

---

compose.yaml

Exposes the NGINX containers to make it easy to debug, `curl` the API, etc

Expose NGINX containers

---

docker/Dockerfile

Bump NGINX Plus to R31

---

.github/workflows/ci.yml

The test was not returning a failure

Split clients test to return errors

---

docker/Dockerfile

Bump NGINX Plus to R32

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependency-review.yml
.github/workflows/fossa.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml

Replaces manual install of yamllint with an Action. This also adds annotations to the files.
This also updates the `checkout` action that was stuck and not updated by dependabot

Use yamllint action from reviewdog

---

.pre-commit-config.yaml

Adds missing yamllint from pre-commit config

Add yamllint to pre-commit config

---

.github/workflows/f5-cla.yml
.yamllint.yaml
CONTRIBUTING.md

Use CLA GitHub Action

---

CONTRIBUTING.md

Make hyperlink text have more context.

Address markdown lint feedback

---

.github/workflows/scorecard.yml

Update to use GITHUB_TOKEN for scorecard reports

Update to use GITHUB_TOKEN for scorecard reports

---

go.mod
tests/client_no_stream_test.go
tests/client_test.go

Prior to release of v3.0.0, update internal references to the library version.

Update to v3 client
